# Site settings
title: Krakowski Klub go
email: krakowski.klub.go@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Strona opisująca działalność Krakowskiego Klubu Go
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://krakow.go.art.pl" # the base hostname & protocol for your site


markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-language-plugin

# jekyll language plugin config
language_data: data.lang.%%
language_includes_dir: _i18n

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
