name: Build & Upload Site

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # can change this to 2.7 or whatever version you prefer

    - name: install dependencies & build site
      uses: limjh16/jekyll-action-ts@v2
      with:
        enable_cache: true
    
    - name: install ncftp
      run: |
        sudo apt-get install -y ncftp
    
    - name: Upload site to FTP.
      env: 
        ftp_location: ${{ secrets.ftp_location }}
        ftp_username: ${{ secrets.ftp_username }}
        ftp_password: ${{ secrets.ftp_password }} 
      run: |
        ncftpput -R -v -u "$ftp_username" -p "$ftp_password" $ftp_location /public_html/ _site/*
